---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resourceNames:
  - system:nodes
  resources:
  - groups
  verbs:
  - impersonate
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resourceNames:
  - system:node:nebula-aws
  - system:node:nebula-fake
  - system:node:nebula-modal
  resources:
  - users
  verbs:
  - impersonate
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - create
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - nebula-kubelet-serving-nebula-aws
  - nebula-kubelet-serving-nebula-fake
  - nebula-kubelet-serving-nebula-modal
  resources:
  - certificatesigningrequests
  verbs:
  - delete
  - get
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - nebula-kubelet-serving-nebula-aws
  - nebula-kubelet-serving-nebula-fake
  - nebula-kubelet-serving-nebula-modal
  resources:
  - certificatesigningrequests/approval
  verbs:
  - update
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - kubernetes.io/kubelet-serving
  resources:
  - signers
  verbs:
  - approve
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nebula.inftyai.com
  resources:
  - nodeclaims
  - nodepools
  - sandboxes
  - sandboxsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nebula.inftyai.com
  resources:
  - nodeclaims/finalizers
  - nodepools/finalizers
  - sandboxes/finalizers
  - sandboxsets/finalizers
  verbs:
  - update
- apiGroups:
  - nebula.inftyai.com
  resources:
  - nodeclaims/status
  - nodepools/status
  - sandboxes/status
  - sandboxsets/scale
  - sandboxsets/status
  verbs:
  - get
  - patch
  - update
